version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_northwind
    env_file:
      - ./var/postgres.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_northwind
    env_file:
      - ./var/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
